import type { WeaponData, PowerUpType } from './types';

export const GAME_CONSTANTS = {
  TICK_RATE: 60,
  TICK_INTERVAL: 1000 / 60,
  MAP_WIDTH: 3000,
  MAP_HEIGHT: 1600,
  GRAVITY_Y: -12,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_SPEED: 200,
  PLAYER_SPRINT_SPEED: 300,
  JUMP_FORCE: 400,
  JETPACK_FORCE: 300,
  JETPACK_MAX_FUEL: 100,
  JETPACK_FUEL_DRAIN: 20,
  JETPACK_FUEL_REGEN: 10,
  MAX_HEALTH: 100,
  RESPAWN_TIME: 3000,
  MATCH_DURATION: 600,
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  COUNTDOWN_TIME: 5,
  MAX_GRENADES: 5,
  GRENADE_FUSE_TIME: 3,
  GRENADE_EXPLOSION_RADIUS: 80,
  GRENADE_DAMAGE: 60,
  GRENADE_SPEED: 400,
  PROJECTILE_SPEED: 600,
  KILL_FEED_DURATION: 5000,
  INTERPOLATION_DELAY: 100,
  INPUT_BUFFER_SIZE: 10,

  KNOCKBACK_BASE: 3.0,
  KNOCKBACK_SCALE: 0.15,

  POWER_UP_SPAWN_INTERVAL: 15,
  POWER_UP_MAX_ACTIVE: 5,
  POWER_UP_PICKUP_RADIUS: 40,

  BOX_DESTRUCTION_PARTICLES: 8,
} as const;

export const WEAPONS: Record<string, WeaponData> = {
  assault_rifle: {
    id: 'assault_rifle',
    name: 'Assault Rifle',
    damage: 15,
    fireRate: 8,
    spread: 0.05,
    range: 500,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 600,
    ammo: 30,
    reloadTime: 2.0,
    knockback: 3,
    damageType: 'bullet',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 45,
    fireRate: 1,
    spread: 0.15,
    range: 250,
    pellets: 6,
    explosionRadius: 0,
    projectileSpeed: 500,
    ammo: 8,
    reloadTime: 2.5,
    knockback: 20,
    damageType: 'bullet',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    damage: 80,
    fireRate: 0.8,
    spread: 0.01,
    range: 1200,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 1200,
    ammo: 5,
    reloadTime: 3.0,
    knockback: 15,
    damageType: 'bullet',
  },
  rocket_launcher: {
    id: 'rocket_launcher',
    name: 'Rocket Launcher',
    damage: 90,
    fireRate: 0.5,
    spread: 0.02,
    range: 800,
    pellets: 1,
    explosionRadius: 80,
    projectileSpeed: 350,
    ammo: 4,
    reloadTime: 3.5,
    knockback: 40,
    damageType: 'explosive',
  },
  smg: {
    id: 'smg',
    name: 'SMG',
    damage: 10,
    fireRate: 14,
    spread: 0.1,
    range: 400,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 550,
    ammo: 35,
    reloadTime: 1.5,
    knockback: 2,
    damageType: 'bullet',
  },
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    damage: 20,
    fireRate: 4,
    spread: 0.03,
    range: 600,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 700,
    ammo: 15,
    reloadTime: 1.2,
    knockback: 5,
    damageType: 'bullet',
  },
  energy_rifle: {
    id: 'energy_rifle',
    name: 'Energy Rifle',
    damage: 25,
    fireRate: 3,
    spread: 0.02,
    range: 700,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 900,
    ammo: 20,
    reloadTime: 2.5,
    knockback: 8,
    damageType: 'energy',
  },
  melee: {
    id: 'melee',
    name: 'Blade',
    damage: 55,
    fireRate: 2,
    spread: 0,
    range: 60,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 0,
    ammo: Infinity,
    reloadTime: 0,
    knockback: 30,
    damageType: 'melee',
  },
  grenade_launcher: {
    id: 'grenade_launcher',
    name: 'Grenade Launcher',
    damage: 70,
    fireRate: 1.2,
    spread: 0.04,
    range: 600,
    pellets: 1,
    explosionRadius: 70,
    projectileSpeed: 400,
    ammo: 6,
    reloadTime: 3.0,
    knockback: 25,
    damageType: 'explosive',
  },
  laser: {
    id: 'laser',
    name: 'Laser Cannon',
    damage: 35,
    fireRate: 2,
    spread: 0.01,
    range: 900,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 1500,
    ammo: 12,
    reloadTime: 3.0,
    knockback: 5,
    damageType: 'energy',
  },
};

export const POWER_UP_CONFIG: Record<PowerUpType, {
  name: string;
  duration: number;
  magnitude: number;
  color: number;
}> = {
  health: { name: 'Health Pack', duration: 0, magnitude: 50, color: 0x22C55E },
  speed: { name: 'Speed Boost', duration: 8, magnitude: 1.5, color: 0x3B82F6 },
  damage: { name: 'Damage Boost', duration: 10, magnitude: 2.0, color: 0xEF4444 },
  shield: { name: 'Shield', duration: 8, magnitude: 0.5, color: 0xA855F7 },
  jetpack_fuel: { name: 'Fuel Pack', duration: 0, magnitude: 50, color: 0xF59E0B },
};

export const THEME = {
  primary: '#2F80ED',
  secondary: '#FF6B00',
  background: '#0F172A',
  surface: '#1E293B',
  success: '#22C55E',
  danger: '#EF4444',
  text: '#F8FAFC',
  textMuted: '#94A3B8',
  border: '#334155',
} as const;

export const SOCKET_EVENTS = {
  // Client -> Server
  JOIN_ROOM: 'room:join',
  CREATE_ROOM: 'room:create',
  LEAVE_ROOM: 'room:leave',
  READY_UP: 'room:ready',
  PLAYER_INPUT: 'game:input',
  SWITCH_WEAPON: 'game:weapon',
  THROW_GRENADE: 'game:grenade',
  GET_ROOMS: 'room:list',
  GET_LEADERBOARD: 'leaderboard:get',

  // Server -> Client
  ROOM_UPDATE: 'room:update',
  MATCH_START: 'game:start',
  MATCH_STATE: 'game:state',
  MATCH_END: 'game:end',
  PLAYER_DIED: 'game:death',
  PLAYER_RESPAWNED: 'game:respawn',
  KILL_FEED: 'game:killfeed',
  COUNTDOWN: 'game:countdown',
  ERROR: 'error',

  // Auth
  GUEST_LOGIN: 'auth:guest',
  AUTH_SUCCESS: 'auth:success',
} as const;
