import type { WeaponData } from './types';

export const GAME_CONSTANTS = {
  TICK_RATE: 60,
  TICK_INTERVAL: 1000 / 60,
  MAP_WIDTH: 3000,
  MAP_HEIGHT: 1600,
  GRAVITY_Y: -12,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_SPEED: 200,
  PLAYER_SPRINT_SPEED: 300,
  JUMP_FORCE: 400,
  JETPACK_FORCE: 300,
  JETPACK_MAX_FUEL: 100,
  JETPACK_FUEL_DRAIN: 20,
  JETPACK_FUEL_REGEN: 10,
  MAX_HEALTH: 100,
  RESPAWN_TIME: 3000,
  MATCH_DURATION: 600,
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  COUNTDOWN_TIME: 5,
  MAX_GRENADES: 5,
  GRENADE_FUSE_TIME: 3,
  GRENADE_EXPLOSION_RADIUS: 80,
  GRENADE_DAMAGE: 60,
  GRENADE_SPEED: 400,
  PROJECTILE_SPEED: 600,
  KILL_FEED_DURATION: 5000,
  INTERPOLATION_DELAY: 100,
  INPUT_BUFFER_SIZE: 10,
} as const;

export const WEAPONS: Record<string, WeaponData> = {
  assault_rifle: {
    id: 'assault_rifle',
    name: 'Assault Rifle',
    damage: 15,
    fireRate: 8,
    spread: 0.05,
    range: 500,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 600,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 45,
    fireRate: 1,
    spread: 0.15,
    range: 250,
    pellets: 6,
    explosionRadius: 0,
    projectileSpeed: 500,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    damage: 80,
    fireRate: 0.8,
    spread: 0.01,
    range: 1200,
    pellets: 1,
    explosionRadius: 0,
    projectileSpeed: 1200,
  },
  rocket_launcher: {
    id: 'rocket_launcher',
    name: 'Rocket Launcher',
    damage: 90,
    fireRate: 0.5,
    spread: 0.02,
    range: 800,
    pellets: 1,
    explosionRadius: 80,
    projectileSpeed: 350,
  },
};

export const THEME = {
  primary: '#2F80ED',
  secondary: '#FF6B00',
  background: '#0F172A',
  surface: '#1E293B',
  success: '#22C55E',
  danger: '#EF4444',
  text: '#F8FAFC',
  textMuted: '#94A3B8',
  border: '#334155',
} as const;

export const SOCKET_EVENTS = {
  // Client -> Server
  JOIN_ROOM: 'room:join',
  CREATE_ROOM: 'room:create',
  LEAVE_ROOM: 'room:leave',
  READY_UP: 'room:ready',
  PLAYER_INPUT: 'game:input',
  SWITCH_WEAPON: 'game:weapon',
  THROW_GRENADE: 'game:grenade',
  GET_ROOMS: 'room:list',
  GET_LEADERBOARD: 'leaderboard:get',

  // Server -> Client
  ROOM_UPDATE: 'room:update',
  MATCH_START: 'game:start',
  MATCH_STATE: 'game:state',
  MATCH_END: 'game:end',
  PLAYER_DIED: 'game:death',
  PLAYER_RESPAWNED: 'game:respawn',
  KILL_FEED: 'game:killfeed',
  COUNTDOWN: 'game:countdown',
  ERROR: 'error',

  // Auth
  GUEST_LOGIN: 'auth:guest',
  AUTH_SUCCESS: 'auth:success',
} as const;
